language: php
php: 7.3

install: true
script: true

before_deploy:
- nvm install 10
- node -v
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
- export PATH="$HOME/.yarn/bin:$PATH"
- curl -sSL https://raw.githubusercontent.com/bs-community/release-script/master/release.sh | bash

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: blessing-skin-server-$TRAVIS_TAG.zip
  name: $TRAVIS_TAG
  draft: true
  skip_cleanup: true
  on:
    tags: true
