name: CI

on: [push]

jobs:
  php73:
    name: PHP Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Prepare
      run: |
        cp .env.example .env
        php artisan key:generate
    - name: Validate Twig templates
      run: php artisan twig:lint -v
  frontend:
    name: JavaScript Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: yarn
    - name: Run checks
      run: |
        yarn lint
        yarn tsc -p .
