name: Telegram

on:
  push:
    branches:
      - dev

jobs:
  notification:
    name: Send Message
    runs-on: ubuntu-latest
    steps:
    - name: Download bot
      run: |
        $botRelease = (Invoke-WebRequest 'https://api.github.com/repos/bs-community/telegram-bot/releases/latest').Content | ConvertFrom-Json
        $botBinUrl = ((Invoke-WebRequest $botRelease.assets_url).Content | ConvertFrom-Json).browser_download_url
        bash -c "curl -fSL $botBinUrl -o bot"
        chmod +x ./bot
      shell: pwsh
    - name: Run bot
      run: ./bot diff
      shell: pwsh
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
